// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMe-BxsuXgj0hwX3AjNO5PW9YfUfBMGBU',
    appId: '1:388438593723:web:7dd0103f71d695aada999e',
    messagingSenderId: '388438593723',
    projectId: 'excluidos-unidos',
    authDomain: 'excluidos-unidos.firebaseapp.com',
    storageBucket: 'excluidos-unidos.appspot.com',
    measurementId: 'G-MRD90ZPERC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYe3FzcROLhcaMPkmJDryvaTLB7aTG16c',
    appId: '1:388438593723:android:1dfa1f59baf4bc3ada999e',
    messagingSenderId: '388438593723',
    projectId: 'excluidos-unidos',
    storageBucket: 'excluidos-unidos.appspot.com',
  );
}
